_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ip-address-pools.yaml
backups: false
helm: true
helmCrds: false
helmName: metallb
helmRelease: metallb
helmRepo: https://metallb.github.io/metallb
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: true
ingHost: metallb.crt.house
ingName: metallb
ingress: false
labels: ''
name: metallb
namespace: metallb
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://metallb.org
url: https://github.com/charlesthomas/homelab-metallb
