_commit: v1.12.1-1-g902fdaa
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: daemon-sets.yaml,ip-address-pools.yaml,validating-webhook-configurations.yaml
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: ''
name: metallb
namespace: metallb
pvc: false
reloader: true
resources:
- crds.yaml
- configmaps.yaml
- deployments.yaml
- rbac.yaml
- secrets.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://metallb.org
url: https://github.com/charlesthomas/homelab-metallb
