---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-metallb

resources:
- resources/ip-address-pools.yaml
- resources/namespaces.yaml
helmCharts:
- name: metallb
  namespace: metallb
  releaseName: metallb
  repo: https://metallb.github.io/metallb
  valuesFile: helm/values.yaml
