---
apiVersion: v1
kind: Secret
metadata:
  name: frr-k8s-webhook-server-cert
  namespace: metallb
---
apiVersion: v1
kind: Secret
metadata:
  name: metallb-webhook-cert
  namespace: metallb
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
